### ISSUE TITLE
c#: DllNotFoundException on net 6 runtime with alpine 3.15

### ISSUE THREAD

**Issue by akryvasheyeu** [epam/DFP#37]
Used official docker image mcr.microsoft.com/dotnet/aspnet:6.0.3-alpine3.15 with glibc 2.30-r0

Any attempt to use Decimal64 fails with:
```bash
# dotnet TestDfp.dll
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'ddfp0x11x25' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libddfp0x11x25: No such file or directory
   at EPAM.Deltix.DFP.NativeImplImport.ddfp0x11x25_subtract(UInt64 a, UInt64 b)
   at EPAM.Deltix.DFP.NativeImplObj.ddfp0x11x25_subtract(UInt64 a, UInt64 b)
   at EPAM.Deltix.DFP.NativeImpl.subtract(UInt64 a, UInt64 b)
   at EPAM.Deltix.DFP.Decimal64.op_Subtraction(Decimal64 a, Decimal64 b)
   at Program.<Main>$(String[] args)
```
but file `/tmp/EPAM.Deltix/DFP/0.11.25.0/amd64/libddfp0x11x25.so` exists

**Comment by agdavydov81** [comment]
Similar reproduced with DFP 0.10.24:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Deltix.DFP.NativeImpl' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DecimalNative2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libDecimalNative2: No such file or directory
   at Deltix.DFP.NativeImports.version()
   at Deltix.DFP.NativeImports.VerifyVersion()
   at Deltix.DFP.NativeImportsWrapper.VerifyVersion()
   at Deltix.DFP.NativeImpl..cctor()
   --- End of inner exception stack trace ---
   at Deltix.DFP.NativeImpl.subtract(UInt64 a, UInt64 b)
   at Deltix.DFP.Decimal64.op_Subtraction(Decimal64 a, Decimal64 b)
   at Program.<Main>$(String[] args) in /home/user/TestDfp/Program.cs:line 9
```

**Comment by akryvasheyeu** [comment]
@agdavydov81 can you check version 0.10.6? this is version that was used by our net.core app before (with net 5 runtime + alpine.3.14 )

**Comment by agdavydov81** [comment]
@akryvasheyeu Same result with 0.10.6:
```
/home/user/TestDfp # /root/.dotnet/dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'Deltix.DFP.NativeImpl' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DecimalNative2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libDecimalNative2: No such file or directory
   at Deltix.DFP.NativeImports.version()
   at Deltix.DFP.NativeImports.VerifyVersion()
   at Deltix.DFP.NativeImportsWrapper.VerifyVersion()
   at Deltix.DFP.NativeImpl..cctor()
   --- End of inner exception stack trace ---
   at Deltix.DFP.NativeImpl.subtract(UInt64 a, UInt64 b)
   at Deltix.DFP.Decimal64.op_Subtraction(Decimal64 a, Decimal64 b)
   at Program.<Main>$(String[] args) in /home/user/TestDfp/Program.cs:line 9

/home/user/TestDfp # ls -l /usr/share/.rtmath/dfp/0.10.6.0/64
total 2404
-rw-r--r--    1 root     root       2459720 Apr  6 09:28 libDecimalNative2.so
```

**Comment by agdavydov81** [comment]
Seems this is only .NET problem.
Java version works fine.

**Comment by agdavydov81** [comment]
The switch to the old NativeUtils do not resolved this problem.

Was tests on the NativeUtils  
Revision: 911d947d96910259f02f4a94c69b3e5fd29eb461  
Date: 11/1/2018 19:28:08

**Comment by agdavydov81** [comment]
I stop wasting time on musl statically linking.
If anyone knows how to do this - write to me.
